name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: Build with Maven
        run: mvn -B clean package

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: final-project-0.0.1-SNAPSHOT
          path: /home/runner/work/final-project/final-project/target/

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: final-project-0.0.1-SNAPSHOT
          path: /home/runner/work/final-project/final-project/target/

      - name: Upload artifact to AWS EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          source: "/home/runner/work/final-project/final-project/target/final-project-0.0.1-SNAPSHOT.war"
          target: "/home/ubuntu/tomcat"
         
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            sudo systemctl stop tomcat
            sudo cp /home/ubuntu/tomcat/github/workspace/target/final-project-0.0.1-SNAPSHOT.war /home/apps/tomcat/webapps/build.war
            sudo systemctl start tomcat
