name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Aquí puedes especificar la rama en la que quieres que se active el workflow

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: Build with Maven
        run: mvn -B clean package

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build  # Este trabajo depende del trabajo 'build'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload artifact to AWS EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          source: ".github/workflows/buildanddeploy.yml"
          target: "/home/ubuntu/tomcat"
         
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            sudo systemctl stop tomcat
            sudo cp /home/ubuntu/tomcat/build.yml /home/apps/tomcat/webapps
            sudo systemctl start tomcat
