name: Build with Maven

on:
  push:
    branches:
      - main  # Aquí puedes especificar la rama en la que quieres que se active el workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: Build with Maven
        run: mvn -B clean package
